"""
AI Bodyguard action layer.

Input:
    analyser output dictionary

Output:
    action plan dictionary

Pipeline:
    scanner.py -> detector.py -> analyser.py -> actions.py
"""

from __future__ import annotations

import json
import sys
from dataclasses import asdict, dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional


# ============================================================
# ACTION TYPES
# ============================================================

class ActionType(str, Enum):
    ALLOW = "ALLOW"
    WARN = "WARN"
    BLOCK = "BLOCK"


# ============================================================
# ACTION MODEL
# ============================================================

@dataclass
class Action:
    action: ActionType
    reason: str
    risk_score: int = 0
    destination: Optional[str] = None
    element_type: Optional[str] = None
    text: Optional[str] = None
    signals: List[str] = field(default_factory=list)
    requires_confirmation: bool = False

    def to_dict(self) -> Dict[str, Any]:
        data = asdict(self)
        data["action"] = self.action.value
        return data


# ============================================================
# ACTION ENGINE
# ============================================================

class ActionEngine:
    """
    Convert analyser output into an action plan.

    This module does NOT calculate risk.
    Risk and ALLOW/WARN/BLOCK decisions come from analyser.py.
    """

    def __init__(
        self,
        warn_requires_confirmation: bool = True
    ):
        self.warn_requires_confirmation = (
            warn_requires_confirmation
        )

    def evaluate(
        self,
        analysis: Dict[str, Any]
    ) -> Dict[str, Any]:

        overall_decision = str(
            analysis.get(
                "overall_decision",
                "ALLOW"
            )
        ).upper()

        findings = analysis.get(
            "findings",
            []
        )

        actions = [
            self._finding_to_action(finding)
            for finding in findings
        ]

        # ----------------------------------------------------
        # PAGE-LEVEL ACTION
        # ----------------------------------------------------

        if overall_decision == ActionType.BLOCK.value:

            page_action = ActionType.BLOCK

            page_reason = (
                "The analyser marked the page as BLOCK."
            )

        elif overall_decision == ActionType.WARN.value:

            page_action = ActionType.WARN

            page_reason = (
                "The analyser marked the page as WARN."
            )

        else:

            page_action = ActionType.ALLOW

            page_reason = (
                "The analyser marked the page as ALLOW."
            )

        # FIX: convenience summary of every unique signal that
        # contributed to this page's actions, so a caller (or the
        # confirmation UI on a WARN) doesn't have to iterate every
        # individual finding just to see what was detected.
        all_signals = sorted({
            signal
            for finding in findings
            for signal in finding.get("signals", [])
        })

        return {
            "page": analysis.get(
                "page",
                {}
            ),

            "overall_decision": overall_decision,

            # Correct field name from analyser.py
            "risk_score": analysis.get(
                "risk_score",
                0
            ),

            "all_signals": all_signals,

            "page_action": {
                "action": page_action.value,

                "reason": page_reason,

                "requires_confirmation": (
                    page_action == ActionType.WARN
                    and self.warn_requires_confirmation
                )
            },

            "actions": actions
        }

    # ========================================================
    # FINDING -> ACTION
    # ========================================================

    def _finding_to_action(
        self,
        finding: Dict[str, Any]
    ) -> Dict[str, Any]:

        decision = str(
            finding.get(
                "decision",
                "ALLOW"
            )
        ).upper()

        if decision == ActionType.BLOCK.value:

            action = ActionType.BLOCK

            reason = self._get_reason(
                finding,
                "Blocked by the analyser."
            )

        elif decision == ActionType.WARN.value:

            action = ActionType.WARN

            reason = self._get_reason(
                finding,
                "Warning generated by the analyser."
            )

        else:

            action = ActionType.ALLOW

            reason = self._get_reason(
                finding,
                "Allowed by the analyser."
            )

        result = Action(
            action=action,

            reason=reason,

            risk_score=int(
                finding.get(
                    "risk_score",
                    0
                ) or 0
            ),

            destination=finding.get(
                "destination"
            ),

            element_type=finding.get(
                "element_type"
            ),

            text=finding.get(
                "text"
            ),

            signals=finding.get(
                "signals",
                []
            ),

            requires_confirmation=(
                action == ActionType.WARN
                and self.warn_requires_confirmation
            )
        )

        return result.to_dict()

    # ========================================================
    # REASON
    # ========================================================

    @staticmethod
    def _get_reason(
        finding: Dict[str, Any],
        default: str
    ) -> str:

        reasons = finding.get(
            "reasons"
        ) or []

        if reasons:
            return " ".join(
                str(reason)
                for reason in reasons
            )

        return default

    # ========================================================
    # EXECUTION CHECK
    # ========================================================

    def can_execute(
        self,
        action: Dict[str, Any]
    ) -> bool:

        action_type = str(
            action.get(
                "action",
                "ALLOW"
            )
        ).upper()

        # BLOCK is never automatically executed.
        if action_type == ActionType.BLOCK.value:
            return False

        # WARN requires confirmation.
        if (
            action_type == ActionType.WARN.value
            and self.warn_requires_confirmation
        ):
            return False

        # ALLOW can be executed.
        return True


# ============================================================
# PUBLIC API
# ============================================================

def build_action_plan(
    analysis: Dict[str, Any],
    warn_requires_confirmation: bool = True
) -> Dict[str, Any]:

    engine = ActionEngine(
        warn_requires_confirmation=(
            warn_requires_confirmation
        )
    )

    return engine.evaluate(
        analysis
    )


# ============================================================
# JSON HELPERS
# ============================================================

def load_analyser_output(
    filename: str = "analyser.json"
) -> Dict[str, Any]:

    """Load analyser output from JSON."""

    with open(
        filename,
        "r",
        encoding="utf-8"
    ) as file:

        return json.load(file)


def save_action_plan(
    action_plan: Dict[str, Any],
    filename: str = "actions.json"
) -> None:

    """Save action plan to JSON."""

    with open(
        filename,
        "w",
        encoding="utf-8"
    ) as file:

        json.dump(
            action_plan,
            file,
            indent=2,
            ensure_ascii=False
        )


# ============================================================
# CLI
# ============================================================

def main() -> None:

    if len(sys.argv) not in {1, 2, 3}:

        print(
            "Usage: python actions.py "
            "[analyser.json] [actions.json]"
        )

        sys.exit(1)

    input_file = (
        sys.argv[1]
        if len(sys.argv) >= 2
        else "analyser.json"
    )

    output_file = (
        sys.argv[2]
        if len(sys.argv) >= 3
        else "actions.json"
    )

    try:

        # 1. Load analyser output
        analysis = load_analyser_output(
            input_file
        )

        # 2. Build action plan
        action_plan = build_action_plan(
            analysis
        )

        # 3. Save action plan
        save_action_plan(
            action_plan,
            output_file
        )

        # 4. Display result
        print(
            json.dumps(
                action_plan,
                indent=2,
                ensure_ascii=False
            )
        )

        print(
            f"\nAction plan saved to: {output_file}"
        )

    except FileNotFoundError:

        print(
            f"File not found: {input_file}"
        )

        sys.exit(1)

    except json.JSONDecodeError:

        print(
            f"Invalid JSON file: {input_file}"
        )

        sys.exit(1)

    except Exception as error:

        print(
            f"Action engine error: {error}"
        )

        sys.exit(1)


if __name__ == "__main__":
    main()